[tool.poetry]
name = "chutils"
version = "1.0.0"
description = ""
authors = ["Sergo <sergeiivanov636@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "chutils", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9"
keyring = "^25.6.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"