"""Генератор расширения Chrome (Manifest v3) для авторизации прокси в Chromium."""

import json
import shutil
import tempfile
from pathlib import Path
from types import TracebackType

from typing_extensions import Self

from chutils.fs import atomic_write, ensure_dir
from chutils.lifecycle import register_cleanup, unregister_cleanup
from chutils.logger import setup_logger
from chutils.scraping.proxy.models import ProxyConfig
from chutils.scraping.proxy.parser import parse_proxy

logger = setup_logger(__name__)


class ChromeProxyExtension:
    """Генератор временного расширения Chrome для аутентификации прокси.

    Решает проблему отсутствия встроенной поддержки аутентификации (`user:password`)
    при запуске Chromium через аргумент `--proxy-server` (например, в nodriver).
    Создает расширение Manifest v3 с перехватом `chrome.webRequest.onAuthRequired`.
    """

    def __init__(
        self,
        proxy: ProxyConfig | str,
        output_dir: Path | str | None = None,
        register_lifecycle_cleanup: bool = True,
    ) -> None:
        """Инициализирует генератор расширения.

        Args:
            proxy: Конфигурация прокси или строка формата прокси.
            output_dir: Опциональная директория для размещения расширения.
            register_lifecycle_cleanup: Автоматически регистрировать удаление директории в chutils.lifecycle.
        """
        self.proxy: ProxyConfig = parse_proxy(proxy)
        self._custom_output_dir: Path | None = (
            Path(output_dir) if output_dir is not None else None
        )
        self._path: Path | None = None
        self._is_temp: bool = False
        self._register_lifecycle: bool = register_lifecycle_cleanup

    @property
    def path(self) -> Path:
        """Возвращает путь к директории расширения (генерирует, если еще не создано).

        Returns:
            Путь к директории расширения на диске.
        """
        if self._path is None:
            self.generate(self._custom_output_dir)
        assert self._path is not None
        return self._path

    def generate(self, output_dir: Path | str | None = None) -> Path:
        """Генерирует файлы manifest.json и background.js расширения.

        Args:
            output_dir: Целевая папка для файлов расширения.

        Returns:
            Путь к сгенерированной директории расширения.
        """
        if output_dir is not None:
            ext_dir = Path(output_dir)
            self._is_temp = False
        elif self._custom_output_dir is not None:
            ext_dir = self._custom_output_dir
            self._is_temp = False
        else:
            ext_dir = Path(tempfile.mkdtemp(prefix="chutils_chrome_proxy_ext_"))
            self._is_temp = True

        ensure_dir(ext_dir)
        self._path = ext_dir

        # 1. Manifest v3
        manifest = {
            "version": "1.0.0",
            "manifest_version": 3,
            "name": "Chutils Proxy Authentication Extension",
            "description": "Provides automatic proxy credentials handling",
            "permissions": [
                "proxy",
                "tabs",
                "unlimitedStorage",
                "storage",
                "webRequest",
                "webRequestAuthProvider",
            ],
            "host_permissions": ["<all_urls>"],
            "background": {"service_worker": "background.js"},
        }
        atomic_write(
            ext_dir / "manifest.json",
            json.dumps(manifest, indent=2, ensure_ascii=False),
        )

        # 2. background.js
        scheme = self.proxy.protocol
        if scheme.startswith("socks"):
            scheme = "socks5"
        elif scheme == "https":
            scheme = "https"
        else:
            scheme = "http"

        bg_lines: list[str] = [
            "// Generated by chutils.scraping.proxy.ChromeProxyExtension",
            "const config = {",
            '  mode: "fixed_servers",',
            "  rules: {",
            "    singleProxy: {",
            f'      scheme: "{scheme}",',
            f'      host: "{self.proxy.host}",',
            f"      port: parseInt({self.proxy.port})",
            "    },",
            '    bypassList: ["localhost", "127.0.0.1"]',
            "  }",
            "};",
            "",
            'chrome.proxy.settings.set({value: config, scope: "regular"}, function() {});',
            "",
        ]

        if self.proxy.has_auth and self.proxy.username and self.proxy.password:
            # Экранируем спецсимволы в js-строках
            u_esc = self.proxy.username.replace('"', '\\"')
            p_esc = self.proxy.password.replace('"', '\\"')
            bg_lines.extend(
                [
                    "function callbackFn(details) {",
                    "  return {",
                    "    authCredentials: {",
                    f'      username: "{u_esc}",',
                    f'      password: "{p_esc}"',
                    "    }",
                    "  };",
                    "}",
                    "",
                    "chrome.webRequest.onAuthRequired.addListener(",
                    "  callbackFn,",
                    '  {urls: ["<all_urls>"]},',
                    "  ['blocking']",
                    ");",
                    "",
                ]
            )

        atomic_write(ext_dir / "background.js", "\n".join(bg_lines))

        if self._register_lifecycle:
            register_cleanup(self._cleanup_callback)

        logger.debug("Сгенерировано расширение прокси: %s", ext_dir)
        return ext_dir

    def get_chrome_args(self) -> list[str]:
        """Возвращает CLI аргументы для запуска Chromium с данным расширением.

        Returns:
            Список флагов командной строки (--load-extension, --disable-extensions-except).
        """
        p_str = str(self.path.resolve())
        return [
            f"--load-extension={p_str}",
            f"--disable-extensions-except={p_str}",
        ]

    def _cleanup_callback(self) -> None:
        """Callback для вызова из реестра lifecycle при завершении процесса."""
        self.cleanup()

    def cleanup(self) -> None:
        """Удаляет директорию расширения и отменяет регистрацию в lifecycle."""
        if self._register_lifecycle:
            unregister_cleanup(self._cleanup_callback)

        if self._path is not None and self._path.exists():
            try:
                shutil.rmtree(self._path, ignore_errors=True)
                logger.debug("Удалена временная директория расширения: %s", self._path)
            except Exception as e:
                logger.warning(
                    "Не удалось удалить директорию расширения %s: %s", self._path, e
                )
            self._path = None

    def __enter__(self) -> Self:
        """Вход в контекстный менеджер (создает расширение).

        Returns:
            Экземпляр ChromeProxyExtension с созданным расширением.
        """
        _ = self.path
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        """Выход из контекстного менеджера (удаляет временную директорию).

        Args:
            exc_type: Тип исключения.
            exc_val: Значение исключения.
            exc_tb: Трассировка стека.
        """
        self.cleanup()
